#!/bin/bash

#gsutil compose gs://ds_tick415/dir/before-aaa.csv gs://ds_tick415/dir/before-aab.csv gs://ds_tick415/dir/before-aac.csv gs://ds_tick415/dir/before-aad.csv gs://ds_tick415/dir/before-aae.csv gs://ds_tick415/dir/before-aaf.csv gs://ds_tick415/dir/before-aag.csv gs://ds_tick415/dir/before-aah.csv gs://ds_tick415/dir/before-aai.csv gs://ds_tick415/dir/before-aaj.csv gs://ds_tick415/dir/before-aak.csv gs://ds_tick415/dir/before-aal.csv gs://ds_tick415/dir/before-aam.csv gs://ds_tick415/dir/before-aan.csv gs://ds_tick415/dir/before-aao.csv gs://ds_tick415/dir/before-aap.csv gs://ds_tick415/dir/before-aaq.csv gs://ds_tick415/dir/before-aar.csv gs://ds_tick415/dir/before-aas.csv gs://ds_tick415/dir/before-aat.csv gs://ds_tick415/dir/before-aau.csv gs://ds_tick415/dir/before-aav.csv gs://ds_tick415/dir/before-aaw.csv gs://ds_tick415/dir/before-aax.csv gs://ds_tick415/dir/before-aay.csv gs://ds_tick415/dir/before-aaz.csv gs://ds_tick415/dir/compose_data/compose_1.csv

#gsutil compose gs://ds_tick415/dir/before-aba.csv gs://ds_tick415/dir/before-abb.csv gs://ds_tick415/dir/before-abc.csv gs://ds_tick415/dir/before-abd.csv gs://ds_tick415/dir/before-abe.csv gs://ds_tick415/dir/before-abf.csv gs://ds_tick415/dir/before-abg.csv gs://ds_tick415/dir/before-abh.csv gs://ds_tick415/dir/before-abi.csv gs://ds_tick415/dir/before-abj.csv gs://ds_tick415/dir/before-abk.csv gs://ds_tick415/dir/before-abl.csv gs://ds_tick415/dir/before-abm.csv gs://ds_tick415/dir/before-abn.csv gs://ds_tick415/dir/before-abo.csv gs://ds_tick415/dir/before-abp.csv gs://ds_tick415/dir/before-abq.csv gs://ds_tick415/dir/before-abr.csv gs://ds_tick415/dir/before-abs.csv gs://ds_tick415/dir/before-abt.csv gs://ds_tick415/dir/before-abu.csv gs://ds_tick415/dir/before-abv.csv gs://ds_tick415/dir/before-abw.csv gs://ds_tick415/dir/before-abx.csv gs://ds_tick415/dir/before-aby.csv gs://ds_tick415/dir/before-abz.csv gs://ds_tick415/dir/compose_data/compose_2.csv;

#gsutil compose gs://ds_tick415/dir/before-aca.csv gs://ds_tick415/dir/before-acb.csv gs://ds_tick415/dir/before-acc.csv gs://ds_tick415/dir/before-acd.csv gs://ds_tick415/dir/before-ace.csv gs://ds_tick415/dir/before-acf.csv gs://ds_tick415/dir/before-acg.csv gs://ds_tick415/dir/before-ach.csv gs://ds_tick415/dir/before-aci.csv gs://ds_tick415/dir/before-acj.csv gs://ds_tick415/dir/before-ack.csv gs://ds_tick415/dir/before-acl.csv gs://ds_tick415/dir/before-acm.csv gs://ds_tick415/dir/before-acn.csv gs://ds_tick415/dir/before-aco.csv gs://ds_tick415/dir/before-acp.csv gs://ds_tick415/dir/before-acq.csv gs://ds_tick415/dir/before-acr.csv gs://ds_tick415/dir/before-acs.csv gs://ds_tick415/dir/before-act.csv gs://ds_tick415/dir/before-acu.csv gs://ds_tick415/dir/before-acv.csv gs://ds_tick415/dir/before-acw.csv gs://ds_tick415/dir/before-acx.csv gs://ds_tick415/dir/before-acy.csv gs://ds_tick415/dir/before-acz.csv gs://ds_tick415/dir/compose_data/compose_3.csv;

#gsutil compose gs://ds_tick415/dir/before-ada.csv gs://ds_tick415/dir/before-adb.csv gs://ds_tick415/dir/before-adc.csv gs://ds_tick415/dir/before-add.csv gs://ds_tick415/dir/before-ade.csv gs://ds_tick415/dir/before-adf.csv gs://ds_tick415/dir/before-adg.csv gs://ds_tick415/dir/before-adh.csv gs://ds_tick415/dir/before-adi.csv gs://ds_tick415/dir/before-adj.csv gs://ds_tick415/dir/before-adk.csv gs://ds_tick415/dir/before-adl.csv gs://ds_tick415/dir/before-adm.csv gs://ds_tick415/dir/before-adn.csv gs://ds_tick415/dir/before-ado.csv gs://ds_tick415/dir/before-adp.csv gs://ds_tick415/dir/compose_data/compose_4.csv

gsutil compose gs://ds_tick415/dir/compose_data/compose_1.csv gs://ds_tick415/dir/compose_data/compose_2.csv gs://ds_tick415/dir/compose_data/compose_3.csv gs://ds_tick415/dir/compose_data/compose_4.csv gs://ds_tick415/dir/compose_data/full_data.csv




